- Apps:
    - Quiz:
        href: http://myhouse.local:8081
        description: Aplikacja edukacyjna
        icon: mdi-school

    - Home API:
        href: http://myhouse.local:8082
        description: FastAPI backend
        icon: mdi-api

    - Caddy test:
        href: http://myhouse.local/whoami
        description: Test reverse proxy
        icon: mdi-server

    - Portainer:
        href: http://myhouse.local:9000
        description: Docker management UI
        icon: portainer
        widget:
          type: portainer
          url: http://portainer:9000
          env: 1
          key: "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}"
          fields: ["running", "stopped", "total"]

    - Glances:
        href: http://myhouse.local:61208
        description: RPi system metrics
        icon: mdi-chart-line

    - System:
      - CPU:
          icon: mdi-cpu-64-bit
          widget:
            type: glances
            url: http://glances:61208
            version: 4
            metric: cpu

      - Memory:
          icon: mdi-memory
          widget:
            type: glances
            url: http://glances:61208
            version: 4
            metric: memory

      - MySpeed:
          href: http://myhouse.local:5216
          description: Testy predkosci internetu
          icon: mdi-speedometer
          widget:
            type: myspeed
            url: http://myspeed:5216
